# Generated by Django 5.2.4 on 2025-07-22 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0002_change_markdown_change_markdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markdown',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Downtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('markdown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downtime_owner', to='current.markdown')),
            ],
        ),
        migrations.AddField(
            model_name='markdown',
            name='downtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_downtime', to='current.downtime'),
        ),
    ]
