# Generated by Django 5.2.4 on 2025-07-26 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0003_alter_markdown_title_downtime_markdown_downtime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Change',
            new_name='TextChange',
        ),
        migrations.RemoveField(
            model_name='markdown',
            name='current',
        ),
        migrations.AddField(
            model_name='markdown',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='markdown',
            name='text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_text', to='current.textchange'),
        ),
        migrations.RemoveField(
            model_name='markdown',
            name='ownership',
        ),
        migrations.CreateModel(
            name='DowntimeChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('markdown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='current.markdown')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='current.downtimechange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='markdown',
            name='downtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_downtime', to='current.downtimechange'),
        ),
        migrations.CreateModel(
            name='OwnershipChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('markdown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='current.markdown')),
                ('owners', models.ManyToManyField(related_name='owners', to=settings.AUTH_USER_MODEL)),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='current.ownershipchange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TitleChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('content', models.CharField(max_length=200)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('markdown', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='current.markdown')),
                ('previous', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='current.titlechange')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='markdown',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_title', to='current.titlechange'),
        ),
        migrations.AddField(
            model_name='markdown',
            name='ownership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_ownership', to='current.ownershipchange'),
        ),
        migrations.DeleteModel(
            name='Downtime',
        ),
    ]
