# Generated by Django 5.2.4 on 2025-07-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0004_rename_change_textchange_remove_markdown_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdown',
            name='index_name',
            field=models.CharField(default='default', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
