# Generated by Django 5.2.4 on 2025-08-01 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0005_markdown_index_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='downtimechange',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_downtime', to='current.downtimechange'),
        ),
        migrations.AddField(
            model_name='ownershipchange',
            name='next',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_ownership', to='current.ownershipchange'),
        ),
        migrations.AddField(
            model_name='textchange',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_text', to='current.textchange'),
        ),
        migrations.AddField(
            model_name='titlechange',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_title', to='current.titlechange'),
        ),
        migrations.AlterField(
            model_name='downtimechange',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_downtime', to='current.downtimechange'),
        ),
        migrations.AlterField(
            model_name='ownershipchange',
            name='previous',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_ownership', to='current.ownershipchange'),
        ),
        migrations.AlterField(
            model_name='textchange',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_text', to='current.textchange'),
        ),
        migrations.AlterField(
            model_name='titlechange',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_title', to='current.titlechange'),
        ),
    ]
