# Generated by Django 5.2.4 on 2025-08-01 23:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0006_downtimechange_next_ownershipchange_next_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdown',
            name='seen',
            field=models.ManyToManyField(blank=True, related_name='user_seen', to=settings.AUTH_USER_MODEL),
        ),
    ]
