# Generated by Django 5.2.4 on 2025-08-05 02:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0007_markdown_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdown',
            name='edited',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='markdown',
            name='edited_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
