# Generated by Django 5.2.4 on 2025-08-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0008_markdown_edited_markdown_edited_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downtimechange',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='markdown',
            options={'ordering': ['-edited']},
        ),
        migrations.AlterModelOptions(
            name='ownershipchange',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='textchange',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='titlechange',
            options={'ordering': ['time']},
        ),
        migrations.RemoveField(
            model_name='markdown',
            name='edited_author',
        ),
    ]
