# Generated by Django 5.2.5 on 2025-09-01 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('current', '0009_alter_downtimechange_options_alter_markdown_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='color',
        ),
    ]
