# Generated by Django 5.2.4 on 2025-08-16 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_delete_file_image_author_image_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='tmp',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
