# Generated by Django 5.2.4 on 2025-08-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_tmp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='image',
            name='active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
